### ISSUE TITLE
webpack dev server support? 

### ISSUE THREAD

**Issue by oliviertassinari** [goldhand/sw-precache-webpack-plugin#17] opened 2016-10-09 15:28 UTC
Reading the README of the project you say that [webpack dev server is not supported](https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/README.md#webpack-dev-server-support). I may be able to help.
But first I need to understand, what the limitations are about?
We could extend the API of [serviceworker-webpack-plugin](https://github.com/oliviertassinari/serviceworker-webpack-plugin) to accept a [generated](https://github.com/GoogleChrome/sw-precache/blob/master/README.md#generateoptions-callback) service worker string.

**Comment by goldhand** [comment] 2016-10-09 19:03
@oliviertassinari I think the issue is that webpack-dev-server serves bundles from memory. This plugin saves a service worker to your build directory. It isn't an input asset for webpack so the service worker isn't bundled or anything (intentionally but there could be other approaches).

**Comment by oliviertassinari** [comment] 2016-10-09 20:04
Thanks, so I feel like I'm going in the right direction. I will try to work on it next weekend.
We should be able to simplify the implementation here.

**Comment by goldhand** [comment] 2016-10-10 15:49
Thanks @oliviertassinari let me know how it goes or if you have any more questions 😄

**Comment by domfarolino** [comment] 2016-11-07 21:57
@oliviertassinari any luck so far?

**Comment by oliviertassinari** [comment] 2016-11-07 22:04
I haven't found time to work on it yet. I'm delaying every week, it's a shame 😁 .

**Comment by Aweary** [comment] 2016-11-08 22:11
@oliviertassinari any chance you could share whatever progress or ideas you have on making this work? I'd really like to get this working for https://github.com/electrode-io/electrode-boilerplate-universal-react-node/pull/40 and am happy to put in the work on it.

**Comment by oliviertassinari** [comment] 2016-11-08 22:44
@Aweary The most challenging part of building [serviceworker-webpack-plugin](https://github.com/oliviertassinari/serviceworker-webpack-plugin) was integrating with the webpack plugin API so that it's serving the `sw.js` and updating it as soon as changes are made.

Here is what I have in mind:
1. Exposing a callback API (at the *serviceworker-webpack-plugin level*) that would allow users to inject some static code into that service worker generated. That would take the asset paths object as a first argument.
2. Use the [generated](https://github.com/GoogleChrome/sw-precache/blob/master/README.md#generateoptions-callback) API to get the service-worker code that is following the options provided by users.
3. Integrate 1. and 2. under the hood so the API exposed keeps the same.

**Comment by oliviertassinari** [comment] 2016-11-11 13:03
>  I think the issue is that webpack-dev-server serves bundles from memory

Right, I though I could have bypassed this limitation with the [generated](https://github.com/GoogleChrome/sw-precache/blob/master/README.md#generateoptions-callback) API, but no. `sw-precache` is still looking in the file system to run some checks.
I have made some wrong assumptions.

I'm closing this issue. I'm gonna use the `precache` API of [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox).

```js
import swPrecache from 'sw-precache';

// ...

      new ServiceWorkerWebpackPlugin({
        entry: path.join(__dirname, 'src/sw.js'),
        excludes: [
          '**/.*',
          '**/*.map',
          '*.html',
        ],
        publicPath: `${__dirname}/`,
        template: (serviceWorkerOption) => {
          return swPrecache.generate({
            staticFileGlobs: serviceWorkerOption.assets,
          });
        },
      }),
```

**Comment by acanimal** [comment] 2016-12-29 11:43
Any solution?

I'm working in a project which uses webpack-dev-middleware so de bundle.js and style.css files and generated on the fly while developing and only are created witin the `public/assets` folders in production.

The problem, as you comment, is if I specify the 
```
        staticFileGlobs: [
          './public/assets/style.css',
          './public/assets/bundle.js',
        ],
```

The files are not included in the service-worker code because they really not exists and are generated on the fly by webpack-dev-middleware.

Is there a way to bypass that limitiation and always include the specified files in the service-worker code? Is it possible and easy to add that options?

Thanks

**Comment by goldhand** [comment] 2016-12-29 16:56
@acanimal not yet. I will reopen the issue though since there seems to be some demand for this feature.

**Comment by acanimal** [comment] 2016-12-30 11:11
Thanks. I follow the code and seems all the values specified in the `staticFileGlob` options are passes to google sw-precache plugin, so I open an question: https://github.com/GoogleChrome/sw-precache/issues/230

**Comment by phun-ky** [comment] 2017-01-16 15:10
Tip: use the `write-file-webpack-plugin` plugin, this will ensure that the given files are written to disk in in dev ;)

**Comment by goldhand** [comment] 2017-01-17 21:18
Does anyone have an example of using @phun-ky suggested `write-file-webpack-plugin` to get this plugin working with webpack-dev-server?

**Comment by cescoferraro** [comment] 2017-02-03 11:07
@phun-ky  @goldhand  @f  If I get this right, if I run both this plugin with write-file-webpack-plugin, my "sw.js" is gonna be forced to written to the file system, and if running with the dev-server/node the filesystem would be memory so webpack-dev-server could catch up? 

```js
new WriteFilePlugin({
    // Write only files that have "sw.js" extension.
    test: /\sw.js$/,
    useHashIndex: true
})
```

**Comment by cescoferraro** [comment] 2017-02-03 13:06
@goldhand I am pretty young and dumb about webpack in general, but the actual file write operation on ly happens here right?
https://github.com/goldhand/sw-precache-webpack-plugin/blob/master/src/index.js#L141
as stated here https://github.com/60frames/webpack-hot-server-middleware/issues/13 simpler plugins like
https://github.com/unindented/stats-webpack-plugin create in-memory files just fine on my node setup.
Cant we apply the same approach here? Maybe another boolean option to choose between writing to the file system  or  memory?

**Comment by NekR** [comment] 2017-02-03 13:11
Problem here is that this plugin uses separate tool (`sw-precache`) and that tool isn't tied to webpack by any means, so it simply writes to the file system now knowing that webpack is intended to write to `memory-fs`.

**Comment by jeffposnick** [comment] 2017-02-03 15:12
@ragingwind released https://github.com/ragingwind/sw-precache-webpack-dev-plugin recently.

I can't personally vouch for it, and I've never seen the need to have `sw-precache` work with your `webpack-dev-server` environment (since I'd normally want cache-first service worker behavior disabled when doing local development), but it might be worth trying out if you see the need?

**Comment by NekR** [comment] 2017-02-03 17:01
@jeffposnick yeah, I thought about it as rare case too, but some people need to test locally push notifications or other SW features, so they use it. But that's still rare case, most often they just do it even though their envs becomes unusable after that.

General suggestion: if you don't use push/sync/etc events in your SW -- just disable it in dev and check "if it's still working" on a separate server (e.g. `http-server`) with productions build or simply on staging server.

**Comment by jeffposnick** [comment] 2017-02-03 17:07
`sw-precache` (and presumably the Webpack plugin) has the [`handleFetch`](https://github.com/GoogleChrome/sw-precache#handlefetch-boolean) parameter for that use case, where you still want a service worker generated (perhaps to pick up things that are pulled in via `importScripts`, like push notifications), but you don't want any of the `fetch` logic to kick in. 

That's what I'd kind of think would be ideal for a local developer environment.

**Comment by goldhand** [comment] 2017-02-04 05:46
@cescoferraro, your thoughts are correct, that is the summary of the problem. I don't know how young you are but you're not dumb.

I want to test @ragingwind solution for webpack-dev-server, if that works, I will use it to add webpack-dev-server support to this plugin. As @jeffposnick mentioned, I also typically do not want super strong caching strategies implemented while I'm developing but there is no question that there is a strong demand for this feature.

**Comment by goldhand** [comment] 2017-02-04 06:04
Looks like using the compiler option, as @cescoferraro mentioned, will solve this. See [this solution](https://github.com/ragingwind/sw-precache-webpack-dev-plugin/blob/d46a8f752b9b272ed445d28b85d2fb43c5135bb7/index.js#L50-L51)

**Comment by ragingwind** [comment] 2017-02-04 07:38
First of all, It has a very limited case of using. The reason why I made up another plugin for `sw-precache` instead of making a PR is that I also think that test and development  with `sw-precache` while developing is not a quite frequency of demand.

However, A few of people, get started with SW recently, who around me would like to test, debug and watch what's going on service worker in local because they want to change configurations frequently while they were developing. So, it was released as another plugin named +dev with a limited purpose.

Second, that plugin doesn't use officially exported APIs from sw-precahse, Using indirection of way for [hashing](https://github.com/ragingwind/sw-precache-webpack-dev-plugin/blob/d46a8f752b9b272ed445d28b85d2fb43c5135bb7/index.js#L26) and [listing](https://github.com/ragingwind/sw-precache-webpack-dev-plugin/blob/d46a8f752b9b272ed445d28b85d2fb43c5135bb7/index.js#L29) file's path 

If I would thought that It's a very useful feature for most of case I will make a PR.

**Comment by goldhand** [comment] 2017-02-04 18:45
@ragingwind I would love to see a pr for this feature. This is the longest running thread/issue with this plugin. I like your dev plugin but I feel that adding a dev configuration flag to this plugin so users can easily opt in to dev support would be really convenient.

**Comment by jlbates** [comment] 2017-04-04 01:23
I'm really missing this right now. 👍

**Comment by goldhand** [comment] 2017-04-16 17:51
Unfortunately, there is no way for sw-precache to work with webpack-dev-server. sw-precache uses paths on the file system to generate the service worker. They don't exist on the file system so this will not be possible.

**Closed by goldhand** 2017-04-16 17:51 UTC
Labels: enhancement

**Comment by ragingwind** [comment] 2017-04-16 20:32
@goldhand I'm sorry for receiving no answer from me. Meanwhile, I was looking for another way to make it to support working on webpack-dev-server for a new PR. However, It reached that there no way for working on web-deb-server unless and until sw-precache supports various files-system, as you mentioned in readme. So, I wouldn't make a PR with vary unstable and workaround code.
