### ISSUE TITLE
runtimeCaching network first then cache

### ISSUE THREAD

**Issue by MuzammilRafay** [goldhand/sw-precache-webpack-plugin#164] opened 2019-07-18 07:39 UTC
Hey i want to first check network then cache if network is not available.
any idea about this pattern in cache ???

runtimeCaching: [
            {
                urlPattern: /^https:\/\/fonts\.googleapis\.com\//,
                handler: 'cacheFirst'
            },
            {
                urlPattern: /^https:\/\/www\.thecocktaildb\.com\/images\/media\/drink\/(\w+)\.jpg/,
                handler: 'cacheFirst'
            }
        ],

**Comment by carlesjavierre** [comment] 2019-10-09 20:52
Did you try with

handler: 'networkFirst'

It happened to work for me.

**Comment by goldhand** [comment] 2020-01-25 13:55
Closing: unable to reproduce

**Closed by goldhand** 2020-01-25 13:55 UTC
